5月17日　進捗報告
tigerscave/eight-js-easy-apps pull request #18
Opened 2023-05-17 10:42 UTC by mre1ght

・ブラウザを開いたときに、【レバー設定、ペダル設定：非表示】　→　【カスタムボタンを押す：表示】にしました。（今は、作業中に逐次設定タブをいじっているため、コメントアウトで無効化しています。）

・レバー設定のプルダウンを実装しました。（伸縮、S、M、起伏から選べるようにしました。）

2023-05-18 07:51 UTC, mre1ght commented
【進捗】
・カスタム設定の編集画面が表示される。
・カスタム設定ボタンを押したら、ペダルとレバーの設定が変更できる。
・ローカルストレージの実装をしました。

【困っていること】
・重複選択すると、ボタンが無効化されるロジック実装については、どのようにすればよいか全くわかりません。詰んでいます。（例えば、項目Aと項目Aが重複して選択されている状況はどのように書けばよいか？問題）

2023-05-19 10:19 UTC, mre1ght commented
カスタムボタンを編集⇔保存の文字切り替えは自力でやりました。isDisabledの切り替えはラハさんに教えてもらいました。
#20

2023-05-19 10:24 UTC, azamiya requested changes

2023-05-19 10:24 UTC, azamiya commented on notepad/main.js
> +今回のアプリでは、メモ帳のテキストを保存するために、memootいうキーを用意する。その値も保存する。
`memootいうキーを用意する。 ` 何語？

2023-05-19 10:24 UTC, azamiya commented on notepad/main.js
> +setaitem（’キー','値'）キーと値のペアをlocalStorrageに保存できる。
`setaitem` ????

2023-05-19 10:24 UTC, azamiya commented on cranetmock/main.js
> +
なにこの謎の改行

2023-05-19 10:24 UTC, azamiya commented on cranetmock/main.js
> +  const LeverChoice = [
なんでここだけ `PascalCase` ?
`camelCase`に統一しよう

2023-05-19 10:24 UTC, azamiya commented on cranetmock/main.js
> +  const LeverSettings = document.querySelectorAll("[id^='lever-list']");
なんでここだけ PascalCase ?
camelCaseに統一しよう

2023-05-19 10:24 UTC, azamiya commented on cranetmock/main.js
> +  const PedalSettings = document.querySelectorAll("[id^='pedal-list']");
なんでここだけ PascalCase ?
camelCaseに統一しよう

2023-05-19 10:24 UTC, azamiya commented on cranetmock/main.js
> +  //カスタム編集ボタンを使う宣言。edit-button
インデントあってないの気持ち悪い

2023-05-19 10:24 UTC, azamiya commented on cranetmock/main.js
> +  // レバー設定ボタン・ペダル設定ボタンが有効になる。
インデントあってないの気持ち悪い

2023-05-19 10:39 UTC, azamiya requested changes

2023-05-19 10:39 UTC, azamiya commented on cranetmock/main.js
> +  const PedalChoice = [
？？？

2023-05-19 10:41 UTC, azamiya approved these changes

2023-05-19 10:42 UTC, azamiya approved these changes

2023-05-19 10:42 UTC, merged