develop
tigerscave/eight-js-easy-apps pull request #28
Opened 2023-07-13 03:27 UTC by mre1ght

なんか、以前のプルリクが残っています。

とりあえず、UGOKU-KUNの初回あげてみます。

2023-07-13 05:53 UTC, mre1ght commented
#27 #29 
I did it !!

2023-07-13 07:25 UTC, mre1ght commented
できる限りの手は尽くしてみましたが、どうにもなりません。今日のところは。
JavaScriptを使用したらできるので、期限が近くなったら、JavaScript使って実装します。

2023-07-17 00:42 UTC, azamiya requested changes

2023-07-17 00:42 UTC, azamiya commented on UGOKU-KUN/index.html
無闇にidつけない。idはjsで使う。classを使って。全部id外して。

2023-07-17 00:42 UTC, azamiya commented on cranet-tx-dummy-mock/style.css
なんで、このPRに違うファイルが混ざってるの？
混ぜないで。

2023-07-17 00:42 UTC, azamiya commented on index.html
> +  <li><a href="UGOKU-KUN/index.html">UGOKU-KUN</a></li>
わざわざ大文字にする必要なし。
`ugoku-kun/index.html`にして

2023-07-17 00:43 UTC, azamiya commented
この意味がわからないPRの名前のつけかたやめて。このPRはなんなの？もっと名前に簡潔な意味を持たせて。

2023-07-17 02:19 UTC, mre1ght commented on index.html
> +  <li><a href="UGOKU-KUN/index.html">UGOKU-KUN</a></li>
訂正しました。

2023-07-17 02:22 UTC, mre1ght commented on cranet-tx-dummy-mock/style.css
間違いです。訂正するには、git rebaseが必要なので、現状は手をつけないでおきます。
次回から気をつけます。

2023-07-17 02:23 UTC, mre1ght commented on UGOKU-KUN/index.html
勉強になりました。訂正しました。

2023-07-17 02:55 UTC, azamiya approved these changes

2023-07-17 02:55 UTC, merged